import { IDay } from "@/types/day"

const now = new Date()

export const days: IDay[] = [
   {
      timestamp: new Date(2026, 3, 14).getTime(),
      tasks: [
         {
            name: "Погладити кота",
            description: null,
            completed: true,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: now.getTime(),
         },
         {
            name: "Погладити кота",
            description: null,
            completed: true,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: now.getTime(),
         },
         {
            name: "Погладити кота",
            description: null,
            completed: false,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: null,
         },
      ],
   },
   {
      timestamp: new Date(2026, 3, 15).getTime(),
      tasks: [
         {
            name: "Погладити кота",
            description: null,
            completed: true,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: now.getTime(),
         },
         {
            name: "Погладити кота",
            description: null,
            completed: true,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: now.getTime(),
         },
         {
            name: "Погладити кота",
            description: null,
            completed: false,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: null,
         },
      ],
   },
   {
      timestamp: new Date(2026, 3, 16).getTime(),
      tasks: [
         {
            name: "Погладити кота1",
            description: "Погладити кота і отримати задоволення",
            completed: true,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: now.getTime(),
         },
         {
            name: "Погладити кота2",
            description: null,
            completed: true,
            project: null,
            priority: 1,
            scheduledFor: now.getTime(),
            createdAt: now.getTime(),
            completedAt: now.getTime(),
         },
         {
            name: "Погладити кота3",
            description: null,
            completed: false,
            project: null,
            priority: 4,
            scheduledFor: null,
            createdAt: now.getTime(),
            completedAt: null,
         },
      ],
   },
]
